In [1]:
import numpy as np
import pandas as pd
import random

In [20]:
obj = pd.Series(np.arange(3.0), index=['a', 'b', 'c' ])
new_obj = obj.drop('c')
obj['a':'b']

a    0.0
b    1.0
dtype: float64

In [28]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2


b    0
e    1
f    2
Name: good, dtype: int64

In [20]:
data = np.random.randn(2, 3)

In [21]:
data

array([[ 0.37886335,  0.82646203, -0.27490864],
       [ 1.55092533, -0.88297675, -0.66335485]])

In [22]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
arr2 = np.arange(15).reshape((3,5))
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
arr2[0:2, 3:5]


array([[3, 4],
       [8, 9]])

In [37]:
df = pd.DataFrame(np.array([random.random()*100 for i in range(16)]).reshape((4,4)),
                 columns=['a', 'b', 'c', 'd'],
                  index=['one', 'two', 'three','four'])
df

a          b          c          d
one    85.361047  52.232378  41.685636  15.890249
two    31.800023  34.030777  12.087647  85.202559
three  21.011596  27.687772  83.685912  28.650819
four   11.932788  98.882522   3.386822  98.529439

In [39]:
df[['b','c']]

b          c
one    52.232378  41.685636
two    34.030777  12.087647
three  27.687772  83.685912
four   98.882522   3.386822

In [44]:
df.iloc[[2,3]]

a          b          c          d
three  21.011596  27.687772  83.685912  28.650819
four   11.932788  98.882522   3.386822  98.529439

In [46]:
df.loc[['two', 'one']]

a          b          c          d
two  31.800023  34.030777  12.087647  85.202559
one  85.361047  52.232378  41.685636  15.890249

In [53]:
df[df > 50]

a          b          c          d
one    85.361047  52.232378        NaN        NaN
two          NaN        NaN        NaN  85.202559
three        NaN        NaN  83.685912        NaN
four         NaN  98.882522        NaN  98.529439

In [63]:
np.mean(df)

a    37.526364
b    53.208362
c    35.211504
d    57.068267
dtype: float64

In [42]:
df.mean()

a    38.496651
b    52.710358
c    61.510298
d    50.878830
dtype: float64

In [41]:
def f(x):
    return x.mean()
df.apply(f)

a    38.496651
b    52.710358
c    61.510298
d    50.878830
dtype: float64

In [8]:
df = pd.DataFrame((np.random.random(16) * 100).reshape((4,4)), 
                  index=['one', 'two','three','four'],
                  columns=list('abcd'))
df

a          b          c          d
one    43.511175  60.814246  95.879872  17.703570
two    21.546173  10.274857  32.933581  75.367567
three  37.491522  67.230796  41.342381  20.169880
four   51.437733  72.521534  75.885360  90.274304

In [23]:
df.shape

(4, 4)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, one to four
Data columns (total 4 columns):
a    4 non-null float64
b    4 non-null float64
c    4 non-null float64
d    4 non-null float64
dtypes: float64(4)
memory usage: 320.0+ bytes


In [25]:
df.describe()

a          b          c          d
count   4.000000   4.000000   4.000000   4.000000
mean   38.496651  52.710358  61.510298  50.878830
std    12.661570  28.692453  29.503015  37.395807
min    21.546173  10.274857  32.933581  17.703570
25%    33.505185  48.179399  39.240181  19.553302
50%    40.501349  64.022521  58.613870  47.768723
75%    45.492814  68.553481  80.883988  79.094251
max    51.437733  72.521534  95.879872  90.274304